-- Analytics and insights tables
CREATE TABLE themes (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(50) CHECK (category IN ('emotion', 'behavior', 'thought', 'relationship', 'event')),
    frequency INTEGER DEFAULT 1,
    sentiment VARCHAR(20) CHECK (sentiment IN ('positive', 'negative', 'neutral', 'mixed')),
    confidence_score DECIMAL(3,2),
    first_detected TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    significance VARCHAR(20) DEFAULT 'medium' CHECK (significance IN ('high', 'medium', 'low'))
);

-- Emotional timeline data
CREATE TABLE emotional_timeline (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    session_id INTEGER REFERENCES sessions(id) ON DELETE CASCADE,
    recorded_date DATE NOT NULL,
    mood_score INTEGER CHECK (mood_score >= 0 AND mood_score <= 10),
    anxiety_score INTEGER CHECK (anxiety_score >= 0 AND anxiety_score <= 10),
    energy_score INTEGER CHECK (energy_score >= 0 AND energy_score <= 10),
    stress_score INTEGER CHECK (stress_score >= 0 AND stress_score <= 10),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Events and milestones
CREATE TABLE timeline_events (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    event_date DATE NOT NULL,
    event_type VARCHAR(50) CHECK (event_type IN ('milestone', 'therapy', 'stress', 'achievement', 'setback', 'insight')),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    impact VARCHAR(20) CHECK (impact IN ('positive', 'negative', 'neutral')),
    intensity INTEGER CHECK (intensity >= 1 AND intensity <= 5),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insights generated by AI
CREATE TABLE insights (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    category VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    confidence_score DECIMAL(3,2),
    actionable BOOLEAN DEFAULT false,
    suggestions TEXT[],
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    viewed BOOLEAN DEFAULT false,
    helpful_rating INTEGER CHECK (helpful_rating >= 1 AND helpful_rating <= 5)
);

-- Visualization data cache
CREATE TABLE visualization_cache (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    visualization_type VARCHAR(50) NOT NULL,
    data_hash VARCHAR(64) NOT NULL,
    visualization_data JSONB NOT NULL,
    parameters JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE
);

-- Create indexes for analytics
CREATE INDEX idx_themes_user_id ON themes(user_id);
CREATE INDEX idx_themes_category ON themes(category);
CREATE INDEX idx_emotional_timeline_user_date ON emotional_timeline(user_id, recorded_date);
CREATE INDEX idx_timeline_events_user_date ON timeline_events(user_id, event_date);
CREATE INDEX idx_insights_user_id ON insights(user_id);
CREATE INDEX idx_insights_viewed ON insights(viewed);
CREATE INDEX idx_visualization_cache_user_type ON visualization_cache(user_id, visualization_type);
